### ISSUE TITLE
parseInt octals issue was fixed by ES5

### ISSUE THREAD

**Issue by qgustavor** [denysdovhan/wtfjs#10]
As in MDN ["ECMAScript 5 removes octal interpretation"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#ECMAScript_5_removes_octal_interpretation). [ES5 compatibility table](http://kangax.github.io/compat-table/es5/#test-Miscellaneous_parseInt_ignores_leading_zeros) shows only Konq 4.14 and obsolete platforms (Opera 12 and older, IE 8 and older, and Rhino) still have this issue.

Not related to octals, but something to add on:
```javascript
// parseInt always convert input to string:
parseInt({toString: () => 2, valueOf: () => 1}) // -> 2
Number({toString: () => 2, valueOf: () => 1}) // -> 1
```

**Comment by denysdovhan** [comment]
Hi, @qgustavor ! Thanks for reaching out!

Could you make a PR?
