### ISSUE TITLE
"function is not a function"

### ISSUE THREAD

**Issue by linegel** [denysdovhan/wtfjs#101]
Looks like a comeback of old fun
https://github.com/denysdovhan/wtfjs#function-is-not-a-function
Tried in nodejs v11.8.0
And chrome 71

class Foo extends null {}
new Foo() instanceof null

Thrown:
TypeError: Super constructor null of Foo is not a constructor
    at new Foo (repl:1:1)

Doesn't look like expected behavior :/ 
In case it's expected then there should be a link to current expected behavior which was bug fixed

**Comment by denysdovhan** [comment]
Please, open a PR 🙏

**Comment by linegel** [comment]
> Please, open a PR 🙏

Sure, just a moment!
