### ISSUE TITLE
Bug in chrome

### ISSUE THREAD

**Issue by linegel** [denysdovhan/wtfjs#103]
![xoyrdcwfhqf21](https://user-images.githubusercontent.com/1746296/52543204-cb53a600-2db8-11e9-8c25-9fad08bf3803.png)

**Comment by izayl** [comment]
https://stackoverflow.com/questions/41679191/why-is-math-pow-sometimes-not-equal-to-in-javascript

**Comment by denysdovhan** [comment]
Amazing. Can anyone open a PR?

**Comment by izayl** [comment]
> Amazing. Can anyone open a PR?

@denysdovhan I have create a pr before, but it's a just bug in v8, so i closed it.

if you think this problem should be shown in this repo, i'll reopen the pr.

https://github.com/denysdovhan/wtfjs/pull/104
