### ISSUE TITLE
Error: spawn less ENOENT

### ISSUE THREAD

**Issue by Sv443** [denysdovhan/wtfjs#109]
I've installed the npm package with `npm i -g wtfjs` but after running `wtfjs` I get this error:

![grafik](https://user-images.githubusercontent.com/38158426/55461993-1c805900-55f6-11e9-9c24-35b4b0490b83.png)

**Comment by Sv443** [comment]
The help command seems to work fine though:

![grafik](https://user-images.githubusercontent.com/38158426/55462091-4afe3400-55f6-11e9-8356-398c031e3043.png)

**Comment by Sv443** [comment]
closing because of no response

**Comment by pupubird** [comment]
gg is there any solution to this

**Comment by denysdovhan** [comment]
@Sv443 @pupubird can you get more context on this? I cannot reproduce this issue.

**Comment by Sv443** [comment]
Was the issue fixed?  
I can't provide more context because I don't have access to the computer anymore.

**Comment by denysdovhan** [comment]
Let's see if anyone with a similar setup will confirm it. The runner was refactored multiple times, so hopefully, this issue was fixed.
