### ISSUE TITLE
Accessing objects with arrays

### ISSUE THREAD

**Issue by namirsab** [denysdovhan/wtfjs#11]
I find this one really funny as well:

```js
var obj = { prop: 3 }
obj[['prop']] // -> 3
```

Of course the explanation is easy, the bracket operator converts everything you pass to a string, and converting an 1 element array to string is just returning the conversion of that element to string.

**Comment by zswang** [comment]
Multidimensional array

```js
var map = {};
var x = 1;
var y = 2;
var z = 3;

map[[x, y, z]] = true;
map[[x + 10, y, z]] = true;

map["1,2,3"] // -> true
map["11,2,3"] // -> true
```

**Comment by denysdovhan** [comment]
oh god 

guys, can you please send corresponding PRs?

**Comment by namirsab** [comment]
PR created:
#39
