### ISSUE TITLE
Interactive examples of "It's a fail"

### ISSUE THREAD

**Issue by bluewings** [denysdovhan/wtfjs#115]
I was very impressed to read the articles on this site.
Especially ["It's a fail"](https://github.com/denysdovhan/wtfjs#its-a-fail) The part is interesting, so I've created an example that lets you see the case directly.

https://bluewings.github.io/en/writing-a-sentence-without-using-the-alphabet/#weird-javascript-generator

<a href="https://bluewings.github.io/en/writing-a-sentence-without-using-the-alphabet/#weird-javascript-generator">
<img src="https://user-images.githubusercontent.com/1563202/61621865-aab84200-acae-11e9-9350-aa08ed48d19b.png"></a>

Can I add a link to this example?

**Comment by libook** [comment]
https://github.com/alcuadrado/hieroglyphy

This is a generator too.
