### ISSUE TITLE
Chinese translation seems not using doctoc

### ISSUE THREAD

**Issue by libook** [denysdovhan/wtfjs#120]
I just created a pull request for adding "resolve() won't return Promise instance".
I am chinese, so I have written the Chinese translation, too.
After I ran `npm run toc ./README-zh-cn.md`, I found that doctoc has changed the whole index. Because the previous version directly using Chinese charactors in the index, but doctoc prefer url-encoded.

For more clear git commit record, I restored other indexe lines.

Please check out [this](https://github.com/libook/wtfjs/commit/e2e6be741ceacde4d2ded848d2cfaae53b3be94e#diff-5e594fccdf2704a4953b2f865ec447faL80) to compare 81st line and other lines of index.

**Comment by denysdovhan** [comment]
Now it does. Fixed.
