### ISSUE TITLE
Bug in "Math with true and false"

### ISSUE THREAD

**Issue by sollyucko** [denysdovhan/wtfjs#121]
How does the code given in ["Math with `true` and `false`"](https://github.com/denysdovhan/wtfjs/blob/master/README.md#math-with-true-and-false) work? For me, in Chrome, I get `Uncaught TypeError: true is not a function at <anonymous>:2:7`. Was there a typo or am I confused?

```js
true +
  true(
    // -> 2
    true + true
  ) *
    (true + true) -
  true; // -> 3
```

Same thing in ["Patching numbers"](https://github.com/denysdovhan/wtfjs/blob/master/README.md#patching-numbers):

```js
Number.prototype.isOne = function() {
  return Number(this) === 1;
};

(1.0).isOne(); // -> true
(1).isOne(); // -> true
(2.0)
  .isOne()(
    // -> false
    7
  )
  .isOne(); // -> false
```

**Comment by Mego** [comment]
Looks like bad formatting. It should be:

```js
true + true; // -> 2
(true + true) * (true + true) - true; // -> 3
```

```js
Number.prototype.isOne = function() {
  return Number(this) === 1;
};

(1.0).isOne(); // -> true
(1).isOne(); // -> true
(2.0).isOne(); // -> false
(7).isOne(); // -> false
```

**Comment by denysdovhan** [comment]
This is bad formatting because of Prettier.
