### ISSUE TITLE
Cannot access 'i' before initialization

### ISSUE THREAD

**Issue by Ice-Hazymoon** [denysdovhan/wtfjs#123]
```javascript
window.i = 1
console.log(i)
let i = 2
console.log(i)

// Uncaught ReferenceError: Cannot access 'i' before initialization at <anonymous>:1:3
```

**Comment by Ice-Hazymoon** [comment]
![image](https://user-images.githubusercontent.com/25239977/62457963-69478c80-b7ae-11e9-8a60-f97fd6a511fc.png)
***
![image](https://user-images.githubusercontent.com/25239977/62458070-9f850c00-b7ae-11e9-8005-196e82924789.png)

**Comment by joshabolade** [comment]
You have to re-write your code
you used the variable i and then defined it
define it first then use it.

**Comment by joshabolade** [comment]
let i = 2
window.i = 1
console.log(i)

**Comment by joshabolade** [comment]
> ```js
> window.i = 1
> console.log(i)
> let i = 2
> console.log(i)
> 
> // Uncaught ReferenceError: Cannot access 'i' before initialization at <anonymous>:1:3
> ```

You have to re-write your code
you used the variable i and then defined it
define it first then use it.

let i = 2
window.i = 1
console.log(i)
