### ISSUE TITLE
Translation Request: Japanese

### ISSUE THREAD

**Issue by davidgenesiscruz** [denysdovhan/wtfjs#125]
I am able to translate this language [yes]

**Comment by shimonosatoru** [comment]
I'm also.

**Comment by denysdovhan** [comment]
Any change on opening a PR?

**Comment by davidgenesiscruz** [comment]
@denysdovhan Sorry, I completed missed this!

@shimonosatoru Do you want to translate and I'll check, the other way around? We could also divide the translation work between us and check each other's work.

**Comment by denysdovhan** [comment]
Please, open a PR when you're ready. I am closing this issue.
