### ISSUE TITLE
Translation Request: [French]

### ISSUE THREAD

**Issue by hexangel616** [denysdovhan/wtfjs#131]
I am able to translate this language! I'll start working on it =)

**Comment by Azkun** [comment]
I can help you, i'm french to.

**Comment by hexangel616** [comment]
It's one page, I can manage. =)

**Comment by hexangel616** [comment]
Pull request sent: https://github.com/denysdovhan/wtfjs/pull/133

**Comment by denysdovhan** [comment]
Added by #133
