### ISSUE TITLE
Translation Request: French

### ISSUE THREAD

**Issue by Azkun** [denysdovhan/wtfjs#132]
I am able to translate this language [yes]

**Comment by Azkun** [comment]
i forked, this is almost french : https://github.com/Azkun/wtfjs/

**Comment by hexangel616** [comment]
What's the point of creating another issue for this?

**Comment by Azkun** [comment]
I did not see your issue before doing mine ^^ '

**Comment by hexangel616** [comment]
J'ai fais un pull request: https://github.com/denysdovhan/wtfjs/pull/133
Hésite pas à faire des modifications dessus si tu vois des typos, fautes et/ou non-sens. Pour la tonalité, je suis resté dans celle de la version anglo.

**Comment by denysdovhan** [comment]
Duplicate of #131
