### ISSUE TITLE
Non-strict comparison of a number to true (1 == true)

### ISSUE THREAD

**Issue by markogresak** [denysdovhan/wtfjs#135]
I was goofing around with JS weirdness today, and I found this behaviour, which took me some time to explain to myself. Maybe it could be included in the file? 

It started off with the basic type coercion, which worked as expected:
```js
1 == true
// true
0 == false
// true
```
My initial assumption was that the value is cast to `Boolean`. For this simple example, that assumption would hold
```js
Boolean(1)
// true
Boolean(0)
// false
```

But it broke when trying the following:
```js
1.1 == true
// false
```

Given my original assumption, I was a bit confused because I know `Boolean(1.1) -> true`. 

But the true explanation to the first snippet is:
```js
Number(true)
// 1
Number(false)
// 0
```
Meaning that `true`/`false` is cast to and compared as `Number`.

**Comment by libook** [comment]
```javascript
Boolean(1.1)
// true
```

Hum... interesting.

**Comment by denysdovhan** [comment]
@markogresak could you open a PR?

**Comment by denysdovhan** [comment]
Added with an explanation. Will be published soon.
