### ISSUE TITLE
Translation Request: Hindi

### ISSUE THREAD

**Issue by hidaytrahman** [denysdovhan/wtfjs#138]
I am able to translate this language [yes]

**Comment by denysdovhan** [comment]
@hidaytrahman go ahead and do that!

**Comment by hidaytrahman** [comment]
Thank you, I am on it.

**Comment by hidaytrahman** [comment]
Hi did you check my PR?

**Comment by denysdovhan** [comment]
You should find someone who speaks Hindi to review your translation.

**Comment by denysdovhan** [comment]
Translation PR: #152
