### ISSUE TITLE
Trivia Hack show me Scan Failed WFT submitted to developer Please do some thing of this error I have see this error from 4-5 day

### ISSUE THREAD

**Issue by Lucky13579** [denysdovhan/wtfjs#159]
![Screenshot_20200701_072056](https://user-images.githubusercontent.com/67669046/86196584-27b39300-bb71-11ea-998e-da44068edd67.jpg)

![Screenshot_20200701_072058](https://user-images.githubusercontent.com/67669046/86196585-297d5680-bb71-11ea-92dd-da68be947d52.jpg)

**Comment by denysdovhan** [comment]
This doesn't seem to related to this repo. It's not an application, it's just a note for developers.
