### ISSUE TITLE
Command line usage

### ISSUE THREAD

**Issue by MoonCheung** [denysdovhan/wtfjs#167]
After typing WTFJS from the command line, how do you type to view the javascript weird specification
![image](https://user-images.githubusercontent.com/19801190/98626441-be2c6800-234c-11eb-99b1-aed65591aef8.png)

**Comment by SharakPL** [comment]
Use arrows to move around and `q` to quit

**Comment by MoonCheung** [comment]
@SharakPL Hi, you know how to run it from the command line (WTFJS), but I wonder how to get the weird javascript specification

**Comment by SharakPL** [comment]
You dont't. This simply loads content of README.md in your terminal. You need to scroll through it. You can try https://github.com/ttscoff/mdless for more

**Comment by MoonCheung** [comment]
@SharakPL thank you
