### ISSUE TITLE
"Addition of Regexps" is invalid

### ISSUE THREAD

**Issue by towc** [denysdovhan/wtfjs#177]
The code presented is

```
// Patch a toString method
RegExp.prototype.toString =
  function() {
    return this.source;
  } /
  7 /
  -/5/; // -> 2
```

But when running, that's just `NaN` because it divides a function by 7.

What you probably meant is:

```
// Patch a toString method
RegExp.prototype.toString =
  function() {
    return this.source;
  };
/7/ - /5/; // -> 2
```

**Comment by towc** [comment]
also, can I suggest you use `--> 2` and similar for all the comments meant to show the return value, instead of the standard `//`? Would add to the quirky experience

**Comment by denysdovhan** [comment]
This is probably broken because of Prettier :\

**Comment by denysdovhan** [comment]
Already fixed. Thanks for reporting!
