### ISSUE TITLE
Improve the explanations of examples

### ISSUE THREAD

**Issue by Kishan08** [denysdovhan/wtfjs#19]
> Motivation: **If you are a beginner**, you can use this notes to get deeper dive into the JavaScript. I hope this notes will motivate you to spend more time reading the specification.

I'm beginner in JS, even though i understands most of the examples but the problem is, most of the examples contains ECMA-Spec as a reference for the detailed explanation of the example which is not a beginner friendly approach.

So what i suggest is try to add explanation of examples there only, so that newbies can understands it properly. 

And thanks for all the examples. It really improved my knowledge.

Hope you consider it as a feature request.

**Comment by denysdovhan** [comment]
Nice idea! I agree with you. Would be great if anyone helps with this.
