### ISSUE TITLE
Readme causes GitHub Mobile app and phone crash

### ISSUE THREAD

**Issue by SharakPL** [denysdovhan/wtfjs#234]
Something on the readme.md isn't escaped properly on GitHub Mobile v1.57.0. When I view this project there on Motorola G8 Power (Android 11) after few seconds some Motorola service crashes and restarts or the phone freezes completely and it requires hard reset.

Maybe it would be better to not use all this code on the main readme, and move each section to separate files. At least it would be easier to find the cause.

Or maybe it's as simple as fixing [missing image](https://github.com/denysdovhan/wtfjs/blob/master/README.md#-supporting) (doubt it 😛 )

**Comment by denysdovhan** [comment]
You should report this problem here: https://github.com/github/feedback
