### ISSUE TITLE
super fun!

### ISSUE THREAD

**Issue by brianleroux** [denysdovhan/wtfjs#25]
thx for the props! lots of ppl helped bring wtfjs to fruition --recently rebirthed the site if you're interested in contributing bits there too! https://wtfjs.com (at https://github.com/brianleroux/wtfjs.com)

(sorry for the issue----wish there was a way to send props in github! 🙏 ❤️ )

**Comment by swedenfortrumpcom** [comment]
I dont get it

**Comment by brianleroux** [comment]
clearly!

**Comment by denysdovhan** [comment]
Hey, @brianleroux! Thanks!

I'll gladly help you with a site. Is there any roadmap or plan?

**Comment by brianleroux** [comment]
Nope! I'd like to make it look less… like I did the css lol.
