### ISSUE TITLE
Could join forces?

### ISSUE THREAD

**Issue by njt1982** [denysdovhan/wtfjs#27]
http://javascriptwtf.com/

I started https://github.com/JavascriptWTF/JavascriptWTF.github.io a few weeks before you started your project; I suspect we may have been driven by the same thing ;)

**Comment by denysdovhan** [comment]
cc/ @brianleroux

**Comment by brianleroux** [comment]
Would love some help/PR's to https://github.com/brianleroux/wtfjs !

**Comment by njt1982** [comment]
Ah damnit - didn't know there was already another site ;)
