### ISSUE TITLE
Holes and Trailing Commas in Array

### ISSUE THREAD

**Issue by aemkei** [denysdovhan/wtfjs#29]
Here is another "funny" thing:

```js
a = [,,,];
a.length // ==> 3
a + "" // ==> ",,"
```

see: https://twitter.com/aemkei/status/870252223762243584 and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by denysdovhan** [comment]
Added! Thanks!
