### ISSUE TITLE
parseInt problem

### ISSUE THREAD

**Issue by killa123** [denysdovhan/wtfjs#30]
in [parseInt is a bad guy](https://github.com/denysdovhan/wtfjs#user-content-parseint-is-a-bad-guy) section

> parseInt('08'); // 0

but i have executed the code in chrome and node.js , the result is 8

**Comment by dimitarnestorov** [comment]
Since ES 2015 parseInt's second argument defaults to 10. In other words it will return 0 in an older browser.
