### ISSUE TITLE
more wtfjs

### ISSUE THREAD

**Issue by ratancs** [denysdovhan/wtfjs#43]
1 + "1" is "11"
But,
1 - "1" is 0

-----------

null == 0 is false
null < 0 is false
null <= 0 is true

**Comment by SwiTool** [comment]
+ is the concatenation sign, whereas the - is a math operator

**Comment by SwiTool** [comment]
Wtf markdown è.é
"+" Is the concatenation sign *

**Comment by sdwvit** [comment]
Just for fun

> Object.keys(NaN)
< [] 
> Object.values(NaN)
< []

**Comment by Geo1088** [comment]
This is already covered in ["Funny Math"](https://github.com/denysdovhan/wtfjs#funny-math)
