### ISSUE TITLE
Wiki links to mobile site

### ISSUE THREAD

**Issue by sudo-suhas** [denysdovhan/wtfjs#49]
In the readme, couple of hyperlinks for Wikipedia go to the mobile site:
  - https://en.m.wikipedia.org/wiki/Just_for_Fun
  - https://en.m.wikipedia.org/wiki/IEEE_754

If this isn't intentional, removing the `m.` is enough to fix it. Otherwise, close away!

Very very very minor issue 😁

**Comment by sebastin25** [comment]
#50 there it is
