### ISSUE TITLE
alert(666): Martin Kleppe tweet

### ISSUE THREAD

**Issue by manikantag** [denysdovhan/wtfjs#55]
Hi, I'm very interested in knowing more about a tweet by @aemkei Martin Kleppe (author of jsfuck.com)

[666]['\155\141\160']['\
\143\157\156\163\164\
\162\165\143\164\157\
\162']('\141\154\145\
\162\164(666)')(666)

// alert(666)

https://twitter.com/aemkei/status/897172907222237185

May be good candidate here too. Thanks.

**Comment by aemkei** [comment]
See: https://mathiasbynens.be/notes/javascript-escapes#octal and https://davidwalsh.name/multiline-javascript-strings

**Comment by MapleGu** [comment]
cool~
