### ISSUE TITLE
setTimeout with infinity delay will execute function immediately

### ISSUE THREAD

**Issue by VdustR** [denysdovhan/wtfjs#61]
It's interesting that passing `Infinity` as `delay` parameter while `setTimeout()` called, the function will executed immediately instead of infinity delay.

```javascript
setTimeout(() => console.log('called'), Infinity)
```

**Comment by initbar** [comment]
@VdustR That's really interesting !! I've ran a few more tests and the results are the same:

![screenshot](https://user-images.githubusercontent.com/12630151/29750405-275eb822-8b0d-11e7-8a46-f183c4ef823c.png)

do you recon the `setTimeout` implementation automatically sets timeout to zero when something is immeasurable ?

**Comment by VdustR** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout):

> ### Maximum delay value
> Browsers including Internet Explorer, Chrome, Safari, and Firefox store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2147483647 (about 24.8 days), resulting in the timeout being executed immediately.

If browsers store it as a 32-bit signed integer then it's not `Infinity` anymore.

It's explained that setTimeout receive `msec` as an `Interger` in [MSDN](https://msdn.microsoft.com/en-us/library/ms536753(v=VS.85).aspx), too:
> ### msec [in]
> Type: Integer
> Integer that specifies the number of milliseconds.

According to [Node.js Timer API](https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args):

> Note: When delay is larger than 2147483647 or less than 1, the delay will be set to 1.

I also found [this in w3.org](https://www.w3.org/TR/2011/WD-html5-20110525/timers.html):

> ### 6.3 Timers
> When the above methods are to get the timeout, they must run the following steps:
> 1. Let timeout be the second argument to the method, or zero if the argument was omitted.
> 2. Apply the ToString() abstract operation to timeout, and let timeout be the result. [ECMA262]
> 3. Apply the ToNumber() abstract operation to timeout, and let timeout be the result. [ECMA262]
> 4. If timeout is an Infinity value, a Not-a-Number (NaN) value, or negative, let timeout be zero.
> 5. Round timeout down to the nearest integer, and let timeout be the result.
> 6. Return timeout.

As the 4rd in mentions, `If timeout is an Infinity value, let timeout be zero.`

It's seems like there is some difference between these references (minimum is 1 in node.js and 0 in w3.org).

I have no idea if there is a standard or how the browsers or node.js handle this exactly.

I also found [this article](http://w3help.org/zh-cn/causes/BX9011) about the difference between the browsers in this case:

Environment:
> OS: Windows 7 Ultimate build 7600
> Browsers:
> * IE6
> * IE7
> * IE8
> * Firefox 3.6.9
> * Chrome 7.0.517.5 dev
> * Safari 5.0.2
> * Opera 10.62

Results:
`Firefox`, `Chrome` and `Safari`: executed immediately.
`IE` and `Opera`: never executed

I also tested in some cases:
* Ubuntu 17.04 Firefox 55.0.2 (64-bit)
* Ubuntu 17.04 Google Chrome 60.0.3112.113 (64-bit)
* Ubuntu 17.04 Node.js v8.4.0
* Windows 7 Google Chrome
* Windows 7 IE11

They are all executed immediately.
