### ISSUE TITLE
The tilde(~) operator

### ISSUE THREAD

**Issue by danilosampaio** [denysdovhan/wtfjs#70]
## Tilde operator (~): **-(N+1)**
where **N** is the expression to the right of the tilde

#### String to number:
`console.log(~~"1");   // 1`

#### true/false to 1/0:
`console.log(~~true);  // 1`
`console.log(~~false); // 0`

#### Array/String contains a element/char:
`~someStr.indexOf("a")`
instead of
`someStr.indexOf("a") >= 0`

Source: https://www.joezimjs.com/javascript/great-mystery-of-the-tilde/

**Comment by Pokechu22** [comment]
`~` returns the [bitwise complement](https://en.wikipedia.org/wiki/Bitwise_operation#NOT).  I guess since JS doesn't have real integers this isn't particularly useful, but in other languages that's what `~` is for.

**Comment by pero5ar** [comment]
Putting almost any arithmetic operator in front of an expression in JS will cause the value to convert to a Number, put a "+" or "-" instead of the tilde and you will get similar results. The only valid thing is the indexOf, but in the same manner you can do `1+someStr.indexOf("a")`

**Comment by denysdovhan** [comment]
This is more like a hack. Looks pretty expectable, so I'd prefer not to add it. Anyway, thanks for reporting!
