### ISSUE TITLE
0 == null is false, but 0 == -null is true. WTF?

### ISSUE THREAD

**Issue by honestserpent** [denysdovhan/wtfjs#85]
Can someone explain this?

``` javascript
0 == null -> false
0 == -null -> true

0 === null -> false
0 === -null -> true
```

Wtf?

**Comment by honestserpent** [comment]
@metrue so basically what happens is that with the `-` operator (or even the `+` operator) the `null` is applied `ToNumber` right?

**Comment by metrue** [comment]
@honestserpent I think so.

**Comment by honestserpent** [comment]
Great, thanks for your answer
