### ISSUE TITLE
Translation Request: pt-Br

### ISSUE THREAD

**Issue by ghost** [denysdovhan/wtfjs#87]
I'd like to help translating to brazilian portuguese. There is any procedure or guidelines I should follow?

**Comment by denysdovhan** [comment]
Basically, you should:

1. translate
2. open a PR
3. find a person (native speaker) who would review and approve your translation
4. (optionally) fix possible mistakes after review
5. profit!

**Comment by netojose** [comment]
me too :)

**Comment by daniel-wendhausen-avalara** [comment]
I can help to :)

**Comment by gabrielgns** [comment]
I would also like to help, do you guys still have any interest?

**Comment by tbalmeida** [comment]
@jlozovei and I did it by the end of April, not sure what was missing to be approved though.
Now there's new content, I guess.

**Comment by denysdovhan** [comment]
Closed by #149
