### ISSUE TITLE
Translation Request: Español / Spanish

### ISSUE THREAD

**Issue by chervera** [denysdovhan/wtfjs#91]
I am able to translate this language, and I already started to do it. I have over a 70% of the job done. When I finish I will do a pull request.

**Comment by denysdovhan** [comment]
Hola! You're welcome! Thanks for your effort towards translation to Spanish!

**Comment by denysdovhan** [comment]
Any progress on this?

**Comment by juanmonsalv3** [comment]
I can help if needed

**Comment by chervera** [comment]
I can have it today, but it will need a correction. I will commit a first translation today. :)

**Comment by denysdovhan** [comment]
Waiting for a PR.

**Comment by denysdovhan** [comment]
It's been two years without a PR. Closing this.
